<a href="https://colab.research.google.com/github/Namesakenberg/BrickByBrickML/blob/main/cleaning_merged_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [147]:
import pandas as pd
import numpy as np

In [148]:
df = pd.read_csv('/content/merged_data.csv')

In [149]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [150]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,2.00,9583.0,2087.0,Super Built up area 2087(193.89 sq.m.),4,4,2,not available,"002, Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony this 4 bhk ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of..."
1,9 Bedroom House for sale in Sector 40 Gurgaon,house,independent,5.00,21124.0,2367.0,Plot area 263(219.9 sq.m.),9,9,3+,"servant room,store room","7777, Sector 40 Gurgaon, Gurgaon, Haryana",3.0,North-West,5 to 10 Year Old,"['Huda city centre metro station', 'Axis bank ...",Its wonderfully made 3bhk on each floor with b...,"['10 Wardrobe', '21 Fan', '1 Exhaust Fan', '9 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,3 BHK Flat in Sector 102 Gurgaon,flat,bptp amstoria,1.90,8444.0,2250.0,Super Built up area 2727(253.35 sq.m.)Built Up...,3,3,3+,servant room,"1021, Sector 102 Gurgaon, Gurgaon, Haryana",1.0,North-East,1 to 5 Year Old,"['Early Basket Grocery shop', 'Conscient One M...",This beautiful 3 bhk flat in sector 102 gurgao...,"['5 Fan', '2 Geyser', '5 Light', '4 AC', '1 Mo...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4.5 out ..."
3,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley,1.40,21538.0,650.0,Super Built up area 650(60.39 sq.m.),3,3,3,not available,"Sector-33 Sohna, Gurgaon, Haryana",2.0,NaN,By 2023,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Well maintained, 24 hours security. Playing gr...",[],"['Lift(s)', 'Swimming Pool', 'Park', 'Visitor ...",NaN
4,2 Bedroom House for sale in Sector 9 Gurgaon,house,independent,1.65,18333.0,900.0,Built Up area: 900 (83.61 sq.m.),2,3,0,not available,"Sector 9, Sector 9 Gurgaon, Gurgaon, Haryana",3.0,NaN,undefined,NaN,2bhk residential house for resale in sector 9 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3942 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [152]:
df.shape

(3961, 20)

In [153]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       19
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [154]:
print(df.duplicated().sum())

0

In [155]:
# get the sector of the houses/flat
df['property_name'].value_counts()

property_name
2 BHK Flat in Sohna                                                                      125
3 BHK Flat in Sector 102 Gurgaon                                                          76
3 BHK Flat in Sector 65 Gurgaon                                                           57
3 BHK Flat in Sector 92 Gurgaon                                                           53
3 BHK Flat in Sector 69 Gurgaon                                                           51
2 BHK Flat in Sector 85 Gurgaon                                                           49
3 BHK Flat in Sector 83 Gurgaon                                                           47
3 BHK Flat in Sector 81 Gurgaon                                                           45
3 BHK Flat in Sector 109 Gurgaon                                                          44
3 BHK Flat in Sector 79 Gurgaon                                                           44
3 BHK Flat in Sector 37D Gurgaon                                                          38
2 BHK Flat in Sector 107 Gurgaon                                                          38
3 BHK Flat in Sector 90 Gurgaon                                                           38
3 BHK Flat in Sector 85 Gurgaon                                                           36
3 BHK Flat in Sector 70 Gurgaon                                                           36
2 BHK Flat in Sector 79 Gurgaon                                                           35
3 BHK Flat in Sector 86 Gurgaon                                                           34
3 BHK Flat in Sector 37C Gurgaon                                                          33
2 BHK Flat in Sector 95 Gurgaon                                                           33
4 BHK Flat in Sector 92 Gurgaon                                                           33
4 BHK Flat in Sector 69 Gurgaon                                                           32
3 BHK Flat in Sector 104 Gurgaon                                                          31
2 BHK Flat in Sector 102 Gurgaon                                                          30
3 BHK Flat in Sector 108 Gurgaon                                                          30
3 BHK Flat in Sector 67 Gurgaon                                                           30
3 BHK Flat in Sector 89 Gurgaon                                                           29
4 BHK Flat in Sector 90 Gurgaon                                                           29
3 BHK Flat in Sector-33 Sohna                                                             29
3 BHK Flat in Sector 56 Gurgaon                                                           26
4 BHK Flat in Sector 85 Gurgaon                                                           25
2 BHK Flat in Sector 81 Gurgaon                                                           25
2 BHK Flat in Sector 89 Gurgaon                                                           25
2 BHK Flat in Sector 86 Gurgaon                                                           24
3 BHK Flat in Sector 61 Gurgaon                                                           23
3 BHK Flat in Sector 113 Gurgaon                                                          23
2 BHK Flat in Sector 90 Gurgaon                                                           23
3 BHK Flat in Sector 84 Gurgaon                                                           22
2 BHK Flat in Sector 68 Gurgaon                                                           22
3 BHK Flat in Sector 70A Gurgaon                                                          22
2 BHK Flat in Sector 84 Gurgaon                                                           21
3 BHK Flat in Nirvana Country                                                             20
3 BHK Flat in Sohna                                                                       20
3 BHK Flat in Sector 49 Gurgaon                                                           19
3 BHK Flat in Sector 107 Gurgaon                                                          19
4 Bedroom House for sale in Sector 109 Gurgaon                                            19
2 BHK Flat in Sector 99A Gurgaon                                                          19
3 BHK Flat in Sector 48 Gurgaon                                                           18
2 BHK Flat in Sector 108 Gurgaon                                                          18
2 BHK Flat in Sector 37C Gurgaon                                                          18
2 BHK Flat in Sector 65 Gurgaon                                                           18
3 BHK Flat in Sector 77 Gurgaon                                                           18
2 BHK Flat in Sector-33 Sohna                                                             18
3 BHK Flat in Sector 106 Gurgaon                                                          18
2 BHK Flat in Sector 61 Gurgaon                                                           17
3 BHK Flat in Sector 66 Gurgaon                                                           17
4 Bedroom House for sale in Sector 48 Gurgaon                                             17
4 BHK Flat in Sector 72 Gurgaon                                                           17
5 Bedroom House for sale in DLF Phase 2                                                   16
2 BHK Flat in Sector 103 Gurgaon                                                          16
4 BHK Flat in Sector 81 Gurgaon                                                           15
5 Bedroom House for sale in DLF Phase 1                                                   15
2 BHK Flat in Sector 37D Gurgaon                                                          15
4 BHK Flat in Sector 104 Gurgaon                                                          15
2 BHK Flat in Sector 104 Gurgaon                                                          15
3 BHK Flat in Sector 103 Gurgaon                                                          15
2 BHK Flat in Sector 70A Gurgaon                                                          15
3 BHK Flat in Sector 54 Gurgaon                                                           14
1 BHK Flat in Sohna                                                                       14
4 BHK Flat in Sector 65 Gurgaon                                                           14
2 BHK Flat in Sector 74 Gurgaon                                                           13
4 Bedroom House for sale in Nirvana Country                                               13
2 BHK Flat in Sector 82 Gurgaon                                                           13
3 BHK Flat in Sector 82 Gurgaon                                                           13
2 BHK Flat in Sector 83 Gurgaon                                                           13
2 BHK Flat in Sector 92 Gurgaon                                                           13
3 BHK Flat in Sector 88A Gurgaon                                                          13
2 BHK Flat in Palam Vihar                                                                 12
3 BHK Flat in Sector 99A Gurgaon                                                          12
3 BHK Flat in Sector 95 Gurgaon                                                           12
4 BHK Flat in Sector 37D Gurgaon                                                          12
5 Bedroom House for sale in Sector 109 Gurgaon                                            12
3 BHK Flat in Sector 1 Imt Manesar                                                        11
3 BHK Flat in Sector 71 Gurgaon                                                           11
4 BHK Flat in Sector 110 Gurgaon                                                          10
3 BHK Flat in Sector 22 Gurgaon                                                           10
2 BHK Flat in Sector 67A Gurgaon                                                          10
2 BHK Flat in Sector 113 Gurgaon                                                          10
5 Bedroom House for sale in Sector 66 Gurgaon                                             10
5 Bedroom House for sale in Nirvana Country                                               10
1 BHK Flat in Sector 95 Gurgaon                                                           10
4 BHK Flat in Sector 56 Gurgaon                                                           10
3 BHK Flat in Sector 78 Gurgaon                                                           10
3 BHK Flat in Palam Vihar                                                                 10
2 BHK Flat in Sector 70 Gurgaon                                                            9
2 BHK Flat in Sector 69 Gurgaon                                                            9
3 BHK Flat in Sector 112 Gurgaon                                                           9
3 BHK Flat in Sector 53 Gurgaon                                                            9
2 BHK Flat in Sector 95A Gurgaon                                                           9
5 Bedroom House for sale in Sector 33 Gurgaon                                              9
4 BHK Flat in Sector 111 Gurgaon                                                           9
3 BHK Flat in Sector 67A Gurgaon                                                           9
4 Bedroom House for sale in DLF Phase 1                                                    9
2 BHK Flat in Sector 88A Gurgaon                                                           9
2 BHK Flat in Sector 71 Gurgaon                                                            8
4 BHK Flat in Sector 106 Gurgaon                                                           8
4 BHK Flat in Sector 48 Gurgaon                                                            8
2 BHK Flat in Sector 77 Gurgaon                                                            8
2 BHK Flat in Sector 93 Gurgaon                                                            8
1 BHK Flat in Sector 56 Gurgaon                                                            8
4 Bedroom House for sale in Palam Vihar                                                    8
4 BHK Flat in Sector 113 Gurgaon                                                           8
2 BHK Flat in Sector 99 Gurgaon                                                            8
3 BHK Flat in Sector 72 Gurgaon                                                            8
2 BHK Flat in Sector 106 Gurgaon                                                           8
4 BHK Flat in Sector 67 Gurgaon                                                            8
3 BHK Flat in Sector 82A Gurgaon                                                           8
3 BHK Flat in Sector 63A Gurgaon                                                           8
3 BHK Flat in Sector 63 Gurgaon                                                            7
3 BHK Flat in Sector 76 Gurgaon                                                            7
3 BHK Flat in Dwarka Expressway Gurgaon                                                    7
4 BHK Flat in Sector 112 Gurgaon                                                           7
4 BHK Flat in Sector 109 Gurgaon                                                           7
4 Bedroom House for sale in Sector 70A Gurgaon                                             7
3 BHK Flat in Sector 1A IMT Manesar                                                        7
4 BHK Flat in Sector 108 Gurgaon                                                           7
4 BHK Flat in DLF Phase 5                                                                  7
2 BHK Flat in Sector 63A Gurgaon                                                           7
3 BHK Flat in Sector 111 Gurgaon                                                           7
2 BHK Flat in Sector 3 Gurgaon                                                             7
4 BHK Flat in Sector 103 Gurgaon                                                           7
6 Bedroom House for sale in DLF Phase 1                                                    7
4 BHK Flat in Sector 62 Gurgaon                                                            7
3 Bedroom House for sale in Nirvana Country                                                7
9 Bedroom House for sale in DLF Phase 2                                                    7
4 BHK Flat in Sector 91 Gurgaon                                                            7
2 BHK Flat in Sector 78 Gurgaon                                                            7
4 Bedroom House for sale in Sector 66 Gurgaon                                              7
2 BHK Flat in DLF Phase 4                                                                  6
4 BHK Flat in Sector 99 Gurgaon                                                            6
4 BHK Flat in Sector 82 Gurgaon                                                            6
4 BHK Flat in Sector 70 Gurgaon                                                            6
3 BHK Flat in Sector 59 Gurgaon                                                            6
2 BHK Flat in Sector 36A Gurgaon                                                           6
3 BHK Flat in DLF Phase 4                                                                  6
2 BHK Flat in Laxman Vihar                                                                 6
2 BHK Flat in Sector 33 Gurgaon                                                            6
3 BHK Flat in DLF Phase 5                                                                  6
4 BHK Flat in Sector 84 Gurgaon                                                            6
4 Bedroom House for sale in Sector 82 Gurgaon                                              6
3 BHK Flat in Sector 68 Gurgaon                                                            6
4 Bedroom House for sale in Sushant Lok Phase 3                                            6
2 BHK Flat in Sector 66 Gurgaon                                                            6
4 BHK Flat in Gwal Pahari                                                                  6
2 BHK Flat in Sector 22 Gurgaon                                                            6
4 BHK Flat in Sector 54 Gurgaon                                                            6
4 Bedroom House for sale in DLF Phase 3                                                    6
3 BHK Flat in Sector 36 Sohna                                                              6
4 BHK Flat in Sector 102 Gurgaon                                                           6
4 BHK Flat in Sector 82A Gurgaon                                                           6
3 Bedroom House for sale in Rajendra Park                                                  6
4 BHK Flat in Sector 9A Gurgaon                                                            6
2 BHK Flat in Sector 62 Gurgaon                                                            5
4 BHK Flat in Sector 86 Gurgaon                                                            5
4 Bedroom House for sale in DLF Phase 2                                                    5
3 Bedroom House for sale in Sector 49 Gurgaon                                              5
4 BHK Flat in Sector 60 Gurgaon                                                            5
3 Bedroom House for sale in Laxman Vihar                                                   5
5 Bedroom House for sale in Laxman Vihar                                                   5
2 BHK Flat in Sector 112 Gurgaon                                                           5
4 BHK Flat in Sector 66 Gurgaon                                                            5
2 BHK Flat in Sector 91 Gurgaon                                                            5
3 BHK Flat in Sector 89 A Gurgaon                                                          5
4 BHK Flat in Sector 63 Gurgaon                                                            5
1 BHK Flat in Sector 71 Gurgaon                                                            5
1 BHK Flat in Palam Vihar                                                                  5
5 Bedroom House for sale in Sector 14 Gurgaon                                              5
1 BHK Flat in Sector 36A Gurgaon                                                           5
3 BHK Flat in Sector 60 Gurgaon                                                            5
3 BHK Flat in Gwal Pahari                                                                  5
2 Bedroom House for sale in Laxman Vihar                                                   5
3 BHK Flat in Sector 74 Gurgaon                                                            5
3 BHK Flat in Sushant Lok Phase 1                                                          4
2 BHK Flat in Sector 60 Gurgaon                                                            4
1 BHK Flat in Sector 104 Gurgaon                                                           4
3 BHK Flat in Sector 47 Gurgaon                                                            4
2 Bedroom House for sale in Laxman Vihar Phase 2                                           4
3 Bedroom House for sale in Sector 14 Gurgaon                                              4
4 BHK Flat in Sector 83 Gurgaon                                                            4
5 BHK Flat in Sector 49 Gurgaon                                                            4
3 Bedroom House for sale in Sector 4 Gurgaon                                               4
4 Bedroom House for sale in Sector 26 Gurgaon                                              4
3 BHK Flat in Mehrauli Gurgaon Road                                                        4
2 BHK Flat in Sector 76 Gurgaon                                                            4
4 BHK Flat in Sector 49 Gurgaon                                                            4
3 BHK Flat in Sector 43 Gurgaon                                                            4
3 BHK Flat in Sector 80 Gurgaon                                                            4
4 Bedroom House for sale in Sector 54 Gurgaon                                              4
6 Bedroom House for sale in Palam Vihar                                                    4
4 BHK Flat in Sector 50 Gurgaon                                                            4
6 Bedroom House for sale in DLF Phase 2                                                    4
5 Bedroom House for sale in Sushant Lok Phase 1                                            4
4 Bedroom House for sale in DLF Phase 4                                                    4
5 BHK Flat in Sector 110 Gurgaon                                                           4
3 BHK Flat in Sector 9A Gurgaon                                                            4
4 Bedroom House for sale in Sector 31 Gurgaon                                              4
4 BHK Flat in Sector 52 Gurgaon                                                            4
16 Bedroom House for sale in DLF Phase 1                                                   4
6 Bedroom House for sale in Uppals Southend                                                4
3 Bedroom House for sale in Sector 48 Gurgaon                                              4
3 Bedroom House for sale in Laxman Vihar Phase 2                                           4
1 Bedroom House for sale in Sector 39 Gurgaon                                              3
3 BHK Flat in Sector 52 Gurgaon                                                            3
3 Bedroom House for sale in Sohna Road                                                     3
5 Bedroom House for sale in Jyoti Park                                                     3

In [156]:
print(df['property_name'].isnull().sum())

0

In [157]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [158]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,Sector 69,2.00,9583.0,2087.0,Super Built up area 2087(193.89 sq.m.),4,4,2,not available,"002, Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony this 4 bhk ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of..."
1,9 Bedroom House for sale in Sector 40 Gurgaon,house,independent,Sector 40,5.00,21124.0,2367.0,Plot area 263(219.9 sq.m.),9,9,3+,"servant room,store room","7777, Sector 40 Gurgaon, Gurgaon, Haryana",3.0,North-West,5 to 10 Year Old,"['Huda city centre metro station', 'Axis bank ...",Its wonderfully made 3bhk on each floor with b...,"['10 Wardrobe', '21 Fan', '1 Exhaust Fan', '9 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,3 BHK Flat in Sector 102 Gurgaon,flat,bptp amstoria,Sector 102,1.90,8444.0,2250.0,Super Built up area 2727(253.35 sq.m.)Built Up...,3,3,3+,servant room,"1021, Sector 102 Gurgaon, Gurgaon, Haryana",1.0,North-East,1 to 5 Year Old,"['Early Basket Grocery shop', 'Conscient One M...",This beautiful 3 bhk flat in sector 102 gurgao...,"['5 Fan', '2 Geyser', '5 Light', '4 AC', '1 Mo...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4.5 out ..."
3,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley,Sector-33 Sohna,1.40,21538.0,650.0,Super Built up area 650(60.39 sq.m.),3,3,3,not available,"Sector-33 Sohna, Gurgaon, Haryana",2.0,NaN,By 2023,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Well maintained, 24 hours security. Playing gr...",[],"['Lift(s)', 'Swimming Pool', 'Park', 'Visitor ...",NaN
4,2 Bedroom House for sale in Sector 9 Gurgaon,house,independent,Sector 9,1.65,18333.0,900.0,Built Up area: 900 (83.61 sq.m.),2,3,0,not available,"Sector 9, Sector 9 Gurgaon, Gurgaon, Haryana",3.0,NaN,undefined,NaN,2bhk residential house for resale in sector 9 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [159]:
df['sector']=df['sector'].str.lower()

In [160]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 37c                                                    53
sector 70                                                     53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 54                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sushant lok phase 3                                           16
sector 110                                                    16
sector 99                                                     16
sector 63                                                     15
sector 14                                                     15
sector 60                                                     15
dlf phase 5                                                   14
sector 76                                                     14
sector 52                                                     14
sector 53                                                     14
sector 1 imt manesar                                          14
gwal pahari                                                   14
sector 3                                                      14
rajendra park                                                 14
sector 46                                                     13
laxman vihar phase 2                                          13
sector 36a                                                    13
uppals southend                                               12
sector 31                                                     12
sector 39                                                     12
sector 50                                                     12
sector 38                                                     12
sohna road                                                    12
sector 93                                                     12
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 4                                                       9
ashok vihar phase 2                                            9
sector 95a                                                     9
sector 55                                                      9
south city 1                                                   9
dwarka expressway                                              8
palam vihar extension                                          8
sector 89 a                                                    8
sector 43                                                      8
sector 10a                                                     8
sector 40                                                      8
c block sushant lok phase 1                                    8
malibu town                                                    8
sector 57                                                      8
mehrauli  road                                                 8
sector 59                                                      8
new colony                                                     7
sector 51                                                      7
mianwali colony                                                7
sector 26                                                      7
sector 36 sohna                                                7
surat nagar 1                                                  7
sector 58                                                      7
sector 11                                                      7
ashok vihar                                                    6
jacobpura                                                      6
sector 5                                                       6
rajiv nagar                                                    6
jyoti park                                                     6
sector 1                                                       6
sector 30                                                      5
subhash nagar                                                  5
new palam vihar                                                5
sushant lok phase 2                                            5
sector 2                                                       5
sector 105                                                     5
arjun nagar                                                    5
manesar                                                        5
chakkarpur                                                     5
greenwood city                                                 5
saraswati vihar                                                5
dayanand colony                                                5
sector 28                                                      5
ansal plaza                                                    5
sector 80                                                      5
sector 9                                                       5
sector 23a                                                     5
sector 45                                                      4
sector 3a                                                      4
sector 6                                                       4
surya vihar                                                    4
sector 12a                                                     4
new                                                            4
imt manesar                                                    4
bhim nagar                                                     4
vishnu garden                                                  4
shivpuri                                                       4
baldev nagar                                                   4
devilal colony                                                 4
dharam colony                                                  4
krishna colony                                                 4
sector 12                                                      4
shivaji nagar                                                  4
bhondsi                                                        4
suncity                                                        4
valley view estate                                             4
adarsh nagar                                                   4
sector 17                                                      4
madanpuri                                                      4
ravi nagar                                                     4
garhi harsaru                                                  4
sector 36                                                      4
prem nagar                                                     3
sector 17a                                                     3
sector 110 a                                                   3
mg road                                                        3
sector 88b                                                     3
sector 27                                                      3
sector 15                                                      3
a block sushant lok phase 1                                    3
sector 17b                                                     3
gandhi nagar                                                   3
laxmi garden                                                   3
sector 73                                                      3
maruti kunj                                                    3
b block sushant lok phase 1                                    3
sector 23                                                      3
shakti nagar                                                   3
patel nagar                                                    3
sector 8                                                       3
sector 21                                                      2
surat nagar phase 2                                            2
sheetla colony                                                 2
surat nagar                                                    2
golf course road                                               2
daulatabad                                                     2
ambience island                                                2
acharya puri                                                   2
bhawani enclave                                                2
shanti nagar                                                   2
sector-11 sohna                                                2
sector 15 part 1                                               2
new palam vihar phase 1                                        2
lajpat nagar                                                   2
, delhi ncr                                                    2
sector 15 part 2                                               2
sector 24                                                      2
sector 32                                                      2
hira nagar                                                     2
samaspur                                                       2
mohan nagar                                                    2
manohar nagar                                                  2
rosewood                                                       2
new basti                                                      2
sector 41                                                      2
iffco chowk                                                    2
nars                                                           2
golf course ext road                                           2
block a surya vihar                                            2
mayfield garden                                                2
sohna  road                                                    2
faridabad road                                                 2
farukhnagar                                                    2
pratap nagar                                                   2
sector-2 sohna                                                 2
shankar vihar                                                  2
new palam vihar phase 2                                        2
bissar                                                         2
sushant lok                                                    2
west rajiv nagar                                               2
rajiv chowk                                                    2
sispal vihar                                                   2
huda saraswati vihar                                           1
gopal nagar, garhi ghasita, sonipat                            1
ansal's palam vihar                                            1
sec 3 bhim vihar part 1 bhimgher kheri                         1
heritage city                                                  1
kheri                                                          1
anand garden, sector-105                                       1
new colony, sector 7                                           1
block h ashok vihar phase iii extension                        1
hsiidc plot sector 1 imt manesar                               1
bptp                                                           1
near nand hospital                                             1
dhankot                                                        1
g block dlf city phase 1                                       1
old delhi road, opp sector-14                                  1
saraswati enclave                                              1
b1 block sector 57                                             1
ashok vihar phase 3                                            1
sector 4 urban estate                                          1
laxmna vihar, phase 2                                          1
damdma                                                         1
sector-5 sheetla colony                                        1
hno 13 sagar enclave sura                                      1
sector 9b                                                      1
near pataudi chowk                                             1
saroop garden rajendra park                                    1
ats marigold                                                   1
kanahi                                                         1
jacobpura near sadar bazar                                     1
v block dlf phase 3                                            1
rajiv colony                                                   1
park view                                                      1
mahalaxmi garden, rajendra place                               1
garauli kalan                                                  1
sector 21a faridabad                                           1
near khandsa road                                              1
naharpur rupa                                                  1
jat colony,fazilpur/taj nagar road                             1
sector 17c                                                     1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sector-7 hous                                                  1
tekchand nagar                                                 1
civil l                                                        1
sai kunj                                                       1
cyber city                                                     1
block g sector-57                                              1
south city                                                     1
bhimgarh kheri phase 3                                         1
ravi nager basai road                                          1
near sector 1 market                                           1
carterpuri village                                             1
ram nagar                                                      1
ashok vihar phase i                                            1
mahavir pura                                                   1
sector 13                                                      1
laxman vihar, railway road,                                    1
udyog vihar phase 1                                            1
khandsa                                                        1
vir nagar                                                      1
bhora kalan                                                    1
near euro                                                      1
om nagar                                                       1
urban estate, sector 5                                         1
sector 37a                                                     1
nirvana country pocket h                                       1
part 3 sector 5                                                1
sector 42                                                      1
sector 5 chowk                                                 1
begampur khatola                                               1
godrej aria , sector 79 ,                                      1
rattan garden                                                  1
sultanpur                                                      1
pataudi road                                                   1
sector-5 sohna                                                 1
sector-35 sohna                                                1
sadar bazar                                                    1
shivji park colony                                             1
lucknow                                                        1
new jyoti park                                                 1
alipur                                                         1
sector 37b                                                     1
Name: count, dtype: int64

## Manually replacing the sector for houses not given in the dataset

In [161]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [162]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [163]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [164]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [165]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [166]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [167]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [168]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 50                                                     65
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 2                                                      55
sector 70a                                                    54
sector 37c                                                    53
sector 43                                                     53
sector 70                                                     53
sector 84                                                     51
sector-33 sohna road                                          51
sector 26                                                     50
sector 67                                                     48
sector 49                                                     48
sector 28                                                     47
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
sector 25                                                     43
sector 82                                                     42
sector 61                                                     42
sector 7                                                      39
sector 106                                                    38
sector 4                                                      36
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 12                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 112                                                    24
sector 24                                                     24
sector 57                                                     24
sector 88a                                                    23
sector 105                                                    23
sector 33                                                     23
sector 14                                                     23
sector 111                                                    22
sector 67a                                                    22
sector 11                                                     21
sector 22                                                     20
sector 82a                                                    20
sector 3                                                      20
sector 47                                                     19
sector 78                                                     19
gwal pahari                                                   18
sector 63a                                                    18
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sector 99                                                     16
sector 60                                                     15
sector 63                                                     15
sector 1 manesar                                              14
sector 53                                                     14
sector 52                                                     14
sector 55                                                     14
sector 76                                                     14
sector 46                                                     13
sector 6                                                      13
sector 9                                                      13
sector 4 phase 2                                              13
sector 36a                                                    13
sohna road road                                               12
sector 39                                                     12
sector 31                                                     12
sector 38                                                     12
sector 93                                                     12
sector 3 phase 3 extension                                    11
sector 41                                                     11
sector 9a                                                     11
sector 13                                                     10
sector 1a manesar                                             10
sector 45                                                      9
sector 3 phase 2                                               9
sector 95a                                                     9
manesar                                                        9
sector 17                                                      8
c block sector 43                                              8
sector 23                                                      8
dwarka expressway                                              8
sector 10a                                                     8
sector 2 extension                                             8
sector 40                                                      8
sector 89 a                                                    8
sector 8                                                       8
sector 59                                                      8
sector 36 sohna road                                           7
sector 51                                                      7
sector 58                                                      7
sector 5                                                       6
sector 1                                                       6
sector 21                                                      6
sector 80                                                      5
new sector 2                                                   5
sector 23a                                                     5
sector 30                                                      5
sector 3a                                                      4
sector 12a                                                     4
sector 36                                                      4
new                                                            4
sector 88b                                                     3
sector 17b                                                     3
b block sector 43                                              3
patel nagar                                                    3
a block sector 43                                              3
sector 17a                                                     3
sector 73                                                      3
maruti kunj                                                    3
sector 27                                                      3
sector 110 a                                                   3
sector 15                                                      3
pratap nagar                                                   2
bissar                                                         2
golf course ext road                                           2
manohar nagar                                                  2
iffco chowk                                                    2
sushant lok                                                    2
shankar vihar                                                  2
block a sector 21                                              2
ambience island                                                2
farukhnagar                                                    2
sohna road  road                                               2
surat nagar                                                    2
golf course road                                               2
hira nagar                                                     2
bhawani enclave                                                2
lajpat nagar                                                   2
shanti nagar                                                   2
mohan nagar                                                    2
sector 15 part 2                                               2
sector 32                                                      2
samaspur                                                       2
west sector 13                                                 2
new sector 2 phase 2                                           2
sector-11 sohna road                                           2
new sector 2 phase 1                                           2
faridabad road                                                 2
sector 15 part 1                                               2
surat nagar phase 2                                            2
acharya puri                                                   2
sheetla colony                                                 2
new basti                                                      2
sispal vihar                                                   2
, delhi ncr                                                    2
rajiv chowk                                                    2
daulatabad                                                     2
rosewood                                                       2
nars                                                           2
mayfield garden                                                2
sector-2 sohna road                                            2
hno 13 sagar enclave sura                                      1
bptp                                                           1
sector-5 sheetla colony                                        1
huda sector 28                                                 1
b1 block sector 57                                             1
saraswati enclave                                              1
near pataudi chowk                                             1
sector 9b                                                      1
naharpur rupa                                                  1
park view                                                      1
sector 21a faridabad                                           1
sector 3 phase 3                                               1
damdma                                                         1
near khandsa road                                              1
garauli kalan                                                  1
sector 4 urban estate                                          1
bhimgarh kheri phase 3                                         1
khandsa                                                        1
saroop garden sector 105                                       1
block g sector-57                                              1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sector 12 near sadar bazar                                     1
kanahi                                                         1
ats marigold                                                   1
sector 17c                                                     1
jat colony,fazilpur/taj nagar road                             1
sector-7 hous                                                  1
sai kunj                                                       1
cyber city                                                     1
tekchand nagar                                                 1
rajiv colony                                                   1
v block sector 24                                              1
mahasector 11, rajendra place                                  1
civil l                                                        1
laxmna vihar, phase 2                                          1
sector 4, railway road,                                        1
carterpuri village                                             1
ram nagar                                                      1
udyog vihar phase 1                                            1
near sector 1 market                                           1
near euro                                                      1
bhora kalan                                                    1
sector 50 pocket h                                             1
vir nagar                                                      1
mahavir pura                                                   1
south city                                                     1
ravi nager basai road                                          1
sector 3 phase i                                               1
part 3 sector 5                                                1
sector 37a                                                     1
urban estate, sector 5                                         1
om nagar                                                       1
sector 7, sector 7                                             1
sector 5 chowk                                                 1
kheri                                                          1
sector 42                                                      1
anand garden, sector-105                                       1
block h sector 3 phase iii extension                           1
sec 3 bhim vihar part 1 bhimgher kheri                         1
heritage city                                                  1
ansal's sector 2                                               1
old delhi road, opp sector-14                                  1
g block dlf city phase 1                                       1
begampur khatola                                               1
near nand hospital                                             1
dhankot                                                        1
hsiidc plot sector 1 manesar                                   1
gopal nagar, garhi ghasita, sonipat                            1
godrej aria , sector 79 ,                                      1
rattan garden                                                  1
sultanpur                                                      1
pataudi road                                                   1
sector-5 sohna road                                            1
sector-35 sohna road                                           1
sadar bazar                                                    1
shivji park colony                                             1
lucknow                                                        1
new sector 7                                                   1
alipur                                                         1
sector 37b                                                     1
Name: count, dtype: int64

In [169]:
# remove the localities having value_count lesser than 3
vc = df['sector'].value_counts()[df['sector'].value_counts()>=3]
df = df[df['sector'].isin(vc.index)]

In [170]:
df.loc[:,'sector'] = df['sector'].str.replace('sector 95a','sector 95')
df.loc[:,'sector'] = df['sector'].str.replace('sector 23a','sector 23')
df.loc[:,'sector'] = df['sector'].str.replace('sector 12a','sector 12')
df.loc[:,'sector'] = df['sector'].str.replace('sector 3a','sector 3')
df.loc[:,'sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df.loc[:,'sector'] = df['sector'].str.replace('patel nagar','sector 15')
df.loc[:,'sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df.loc[:,'sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df.loc[:,'sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [171]:

df.loc[:,'sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df.loc[:,'sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df.loc[:,'sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df.loc[:,'sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df.loc[:,'sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df.loc[:,'sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df.loc[:,'sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df.loc[:,'sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [173]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [174]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [175]:
df.shape

(3803, 21)

In [176]:
df.duplicated().sum()

np.int64(0)

In [177]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,2.00,9583.0,2087.0,Super Built up area 2087(193.89 sq.m.),4,4,2,not available,"002, Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony this 4 bhk ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of..."
1,9 Bedroom House for sale in Sector 40 Gurgaon,house,independent,sector 40,5.00,21124.0,2367.0,Plot area 263(219.9 sq.m.),9,9,3+,"servant room,store room","7777, Sector 40 Gurgaon, Gurgaon, Haryana",3.0,North-West,5 to 10 Year Old,"['Huda city centre metro station', 'Axis bank ...",Its wonderfully made 3bhk on each floor with b...,"['10 Wardrobe', '21 Fan', '1 Exhaust Fan', '9 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,3 BHK Flat in Sector 102 Gurgaon,flat,bptp amstoria,sector 102,1.90,8444.0,2250.0,Super Built up area 2727(253.35 sq.m.)Built Up...,3,3,3+,servant room,"1021, Sector 102 Gurgaon, Gurgaon, Haryana",1.0,North-East,1 to 5 Year Old,"['Early Basket Grocery shop', 'Conscient One M...",This beautiful 3 bhk flat in sector 102 gurgao...,"['5 Fan', '2 Geyser', '5 Light', '4 AC', '1 Mo...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4.5 out ..."
3,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley,sector 33,1.40,21538.0,650.0,Super Built up area 650(60.39 sq.m.),3,3,3,not available,"Sector-33 Sohna, Gurgaon, Haryana",2.0,NaN,By 2023,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Well maintained, 24 hours security. Playing gr...",[],"['Lift(s)', 'Swimming Pool', 'Park', 'Visitor ...",NaN
4,2 Bedroom House for sale in Sector 9 Gurgaon,house,independent,sector 9,1.65,18333.0,900.0,Built Up area: 900 (83.61 sq.m.),2,3,0,not available,"Sector 9, Sector 9 Gurgaon, Gurgaon, Haryana",3.0,NaN,undefined,NaN,2bhk residential house for resale in sector 9 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [178]:
df.drop(columns=['property_name','address','description','rating'],inplace=True)

In [179]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
362,flat,experion windchants,sector 112,5.31,11204.0,4739.0,Super Built up area 4739(440.27 sq.m.)Built Up...,4,6,3+,"pooja room,servant room",15.0,South,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","['7 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Power Back-up', 'Feng Shui / Vaastu Complian..."
1747,house,independent,sector 7,0.53,5888.0,900.0,Built Up area: 900 (83.61 sq.m.),2,2,0,not available,1.0,NaN,undefined,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
2659,flat,m3m the marina,sector 68,1.00,12500.0,800.0,Carpet area: 800 (74.32 sq.m.),2,2,3,not available,21.0,NaN,1 to 5 Year Old,"['Airia Mall', 'Southern Peripheral Road', 'So...",NaN,"['Power Back-up', 'Lift(s)', 'Swimming Pool', ..."
3383,house,dlf city plots phase 3,sector 24,5.00,34083.0,1467.0,Plot area 163(136.29 sq.m.),13,13,3+,pooja room,4.0,North,0 to 1 Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...","['1 Water Purifier', '1 Fridge', '21 Fan', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
902,flat,signature global park 4,sector 36,0.82,7585.0,1081.0,Super Built up area 1081(100.43 sq.m.)Carpet a...,3,2,2,not available,2.0,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'The Leaf Mall ...",NaN,"['Lift(s)', 'Park']"

In [180]:
df.duplicated().sum()

np.int64(122)

In [182]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)
from google.colab import files
files.download('gurgaon_properties_cleaned_v1.csv')